<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Zc3jyJQ' shared service.

return $this->privates['.service_locator.Zc3jyJQ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('workshop' => function (): \App\Entity\Workshop {
    return ($this->privates['.errored..service_locator.Zc3jyJQ.App\Entity\Workshop'] ?? $this->load('getWorkshopService.php'));
}));
