<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hXT.oGW' shared service.

return $this->privates['.service_locator.hXT.oGW'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('session' => function () {
    return ($this->services['session'] ?? $this->load('getSessionService.php'));
}, 'workshop' => function (): \App\Entity\Workshop {
    return ($this->privates['.errored..service_locator.hXT.oGW.App\Entity\Workshop'] ?? $this->load('getWorkshop2Service.php'));
}));
