<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SAjoI7s' shared service.

return $this->privates['.service_locator.SAjoI7s'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('newsRepository' => function (): \App\Repository\NewsRepository {
    return ($this->privates['App\Repository\NewsRepository'] ?? $this->load('getNewsRepositoryService.php'));
}));
