<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1Y1uG8Q' shared service.

return $this->privates['.service_locator.1Y1uG8Q'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('schoolStopRepository' => function (): \App\Repository\SchoolStopRepository {
    return ($this->privates['App\Repository\SchoolStopRepository'] ?? $this->load('getSchoolStopRepositoryService.php'));
}));
