<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.08aQTYo' shared service.

return $this->privates['.service_locator.08aQTYo'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('schoolRepository' => function (): \App\Repository\SchoolRepository {
    return ($this->privates['App\Repository\SchoolRepository'] ?? $this->load('getSchoolRepositoryService.php'));
}));
