<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.3WLkTWh.App\Entity\DonationBag' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.3WLkTWh": it references class "App\\Entity\\DonationBag" but no such service exists.');
