<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jVPgoOe' shared service.

return $this->privates['.service_locator.jVPgoOe'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('delivery' => function (): \App\Entity\Delivery {
    return ($this->privates['.errored..service_locator.jVPgoOe.App\Entity\Delivery'] ?? $this->load('getDeliveryService.php'));
}));
