<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MabVHwZ' shared service.

return $this->privates['.service_locator.MabVHwZ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('workshopRepository' => function (): \App\Repository\WorkshopRepository {
    return ($this->privates['App\Repository\WorkshopRepository'] ?? $this->load('getWorkshopRepositoryService.php'));
}));
