<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ArticleController::delete' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController::edit' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController::index' => function () {
    return ($this->privates['.service_locator.62SZVUr'] ?? $this->load('get_ServiceLocator_62SZVUrService.php'));
}, 'App\\Controller\\ArticleController::selection' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\ArticleController::show' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\DeliveryBagController::addToCart' => function () {
    return ($this->privates['.service_locator.vGud83Y'] ?? $this->load('get_ServiceLocator_VGud83YService.php'));
}, 'App\\Controller\\DeliveryBagController::delete' => function () {
    return ($this->privates['.service_locator.4un_9ql'] ?? $this->load('get_ServiceLocator_4un9qlService.php'));
}, 'App\\Controller\\DeliveryBagController::edit' => function () {
    return ($this->privates['.service_locator.4un_9ql'] ?? $this->load('get_ServiceLocator_4un9qlService.php'));
}, 'App\\Controller\\DeliveryBagController::index' => function () {
    return ($this->privates['.service_locator.i9EFuuj'] ?? $this->load('get_ServiceLocator_I9EFuujService.php'));
}, 'App\\Controller\\DeliveryBagController::removeFromCart' => function () {
    return ($this->privates['.service_locator.vGud83Y'] ?? $this->load('get_ServiceLocator_VGud83YService.php'));
}, 'App\\Controller\\DeliveryBagController::show' => function () {
    return ($this->privates['.service_locator.4un_9ql'] ?? $this->load('get_ServiceLocator_4un9qlService.php'));
}, 'App\\Controller\\DeliveryBagController::showCart' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\DeliveryBagController::unsetCart' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\DeliveryBagController::validateCart' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\DeliveryController::delete' => function () {
    return ($this->privates['.service_locator.jVPgoOe'] ?? $this->load('get_ServiceLocator_JVPgoOeService.php'));
}, 'App\\Controller\\DeliveryController::edit' => function () {
    return ($this->privates['.service_locator.jVPgoOe'] ?? $this->load('get_ServiceLocator_JVPgoOeService.php'));
}, 'App\\Controller\\DeliveryController::index' => function () {
    return ($this->privates['.service_locator.ptnIIWn'] ?? $this->load('get_ServiceLocator_PtnIIWnService.php'));
}, 'App\\Controller\\DeliveryController::show' => function () {
    return ($this->privates['.service_locator.jVPgoOe'] ?? $this->load('get_ServiceLocator_JVPgoOeService.php'));
}, 'App\\Controller\\DonationBagController::delete' => function () {
    return ($this->privates['.service_locator.3WLkTWh'] ?? $this->load('get_ServiceLocator_3WLkTWhService.php'));
}, 'App\\Controller\\DonationBagController::edit' => function () {
    return ($this->privates['.service_locator.3WLkTWh'] ?? $this->load('get_ServiceLocator_3WLkTWhService.php'));
}, 'App\\Controller\\DonationBagController::index' => function () {
    return ($this->privates['.service_locator.b5pjVLS'] ?? $this->load('get_ServiceLocator_B5pjVLSService.php'));
}, 'App\\Controller\\DonationBagController::show' => function () {
    return ($this->privates['.service_locator.3WLkTWh'] ?? $this->load('get_ServiceLocator_3WLkTWhService.php'));
}, 'App\\Controller\\FabricController::delete' => function () {
    return ($this->privates['.service_locator.j6g6xTt'] ?? $this->load('get_ServiceLocator_J6g6xTtService.php'));
}, 'App\\Controller\\FabricController::edit' => function () {
    return ($this->privates['.service_locator.j6g6xTt'] ?? $this->load('get_ServiceLocator_J6g6xTtService.php'));
}, 'App\\Controller\\FabricController::index' => function () {
    return ($this->privates['.service_locator.eWPu2Tx'] ?? $this->load('get_ServiceLocator_EWPu2TxService.php'));
}, 'App\\Controller\\FabricController::show' => function () {
    return ($this->privates['.service_locator.j6g6xTt'] ?? $this->load('get_ServiceLocator_J6g6xTtService.php'));
}, 'App\\Controller\\HomeController::concept' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\HomeController::show' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\KidController::create' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController::admin' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController::delete' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController::edit' => function () {
    return ($this->privates['.service_locator.Goy7jhH'] ?? $this->load('get_ServiceLocator_Goy7jhHService.php'));
}, 'App\\Controller\\MemberController::index' => function () {
    return ($this->privates['.service_locator.uO5nSH6'] ?? $this->load('get_ServiceLocator_UO5nSH6Service.php'));
}, 'App\\Controller\\MemberController::new' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController::setSession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController::show' => function () {
    return ($this->privates['.service_locator.Goy7jhH'] ?? $this->load('get_ServiceLocator_Goy7jhHService.php'));
}, 'App\\Controller\\MemberController::unsetSession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\NewsController::delete' => function () {
    return ($this->privates['.service_locator.Ncno5IG'] ?? $this->load('get_ServiceLocator_Ncno5IGService.php'));
}, 'App\\Controller\\NewsController::edit' => function () {
    return ($this->privates['.service_locator.Ncno5IG'] ?? $this->load('get_ServiceLocator_Ncno5IGService.php'));
}, 'App\\Controller\\NewsController::index' => function () {
    return ($this->privates['.service_locator.SAjoI7s'] ?? $this->load('get_ServiceLocator_SAjoI7sService.php'));
}, 'App\\Controller\\NewsController::show' => function () {
    return ($this->privates['.service_locator.Ncno5IG'] ?? $this->load('get_ServiceLocator_Ncno5IGService.php'));
}, 'App\\Controller\\SchoolController::delete' => function () {
    return ($this->privates['.service_locator.yAd9_DO'] ?? $this->load('get_ServiceLocator_YAd9DOService.php'));
}, 'App\\Controller\\SchoolController::edit' => function () {
    return ($this->privates['.service_locator.yAd9_DO'] ?? $this->load('get_ServiceLocator_YAd9DOService.php'));
}, 'App\\Controller\\SchoolController::index' => function () {
    return ($this->privates['.service_locator.08aQTYo'] ?? $this->load('get_ServiceLocator_08aQTYoService.php'));
}, 'App\\Controller\\SchoolController::show' => function () {
    return ($this->privates['.service_locator.yAd9_DO'] ?? $this->load('get_ServiceLocator_YAd9DOService.php'));
}, 'App\\Controller\\SchoolStopController::delete' => function () {
    return ($this->privates['.service_locator.vg9rx_y'] ?? $this->load('get_ServiceLocator_Vg9rxYService.php'));
}, 'App\\Controller\\SchoolStopController::edit' => function () {
    return ($this->privates['.service_locator.vg9rx_y'] ?? $this->load('get_ServiceLocator_Vg9rxYService.php'));
}, 'App\\Controller\\SchoolStopController::index' => function () {
    return ($this->privates['.service_locator.1Y1uG8Q'] ?? $this->load('get_ServiceLocator_1Y1uG8QService.php'));
}, 'App\\Controller\\SchoolStopController::show' => function () {
    return ($this->privates['.service_locator.vg9rx_y'] ?? $this->load('get_ServiceLocator_Vg9rxYService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\SecurityController::registration' => function () {
    return ($this->privates['.service_locator.rFr3Ijd'] ?? $this->load('get_ServiceLocator_RFr3IjdService.php'));
}, 'App\\Controller\\WorkshopController::book' => function () {
    return ($this->privates['.service_locator.hXT.oGW'] ?? $this->load('get_ServiceLocator_HXT_OGWService.php'));
}, 'App\\Controller\\WorkshopController::delete' => function () {
    return ($this->privates['.service_locator.Zc3jyJQ'] ?? $this->load('get_ServiceLocator_Zc3jyJQService.php'));
}, 'App\\Controller\\WorkshopController::edit' => function () {
    return ($this->privates['.service_locator.Zc3jyJQ'] ?? $this->load('get_ServiceLocator_Zc3jyJQService.php'));
}, 'App\\Controller\\WorkshopController::index' => function () {
    return ($this->privates['.service_locator.MabVHwZ'] ?? $this->load('get_ServiceLocator_MabVHwZService.php'));
}, 'App\\Controller\\WorkshopController::pay' => function () {
    return ($this->privates['.service_locator.hXT.oGW'] ?? $this->load('get_ServiceLocator_HXT_OGWService.php'));
}, 'App\\Controller\\WorkshopController::show' => function () {
    return ($this->privates['.service_locator.Zc3jyJQ'] ?? $this->load('get_ServiceLocator_Zc3jyJQService.php'));
}, 'App\\Controller\\ArticleController:delete' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController:edit' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\ArticleController:index' => function () {
    return ($this->privates['.service_locator.62SZVUr'] ?? $this->load('get_ServiceLocator_62SZVUrService.php'));
}, 'App\\Controller\\ArticleController:selection' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\ArticleController:show' => function () {
    return ($this->privates['.service_locator.zv3hrPg'] ?? $this->load('get_ServiceLocator_Zv3hrPgService.php'));
}, 'App\\Controller\\DeliveryBagController:addToCart' => function () {
    return ($this->privates['.service_locator.vGud83Y'] ?? $this->load('get_ServiceLocator_VGud83YService.php'));
}, 'App\\Controller\\DeliveryBagController:delete' => function () {
    return ($this->privates['.service_locator.4un_9ql'] ?? $this->load('get_ServiceLocator_4un9qlService.php'));
}, 'App\\Controller\\DeliveryBagController:edit' => function () {
    return ($this->privates['.service_locator.4un_9ql'] ?? $this->load('get_ServiceLocator_4un9qlService.php'));
}, 'App\\Controller\\DeliveryBagController:index' => function () {
    return ($this->privates['.service_locator.i9EFuuj'] ?? $this->load('get_ServiceLocator_I9EFuujService.php'));
}, 'App\\Controller\\DeliveryBagController:removeFromCart' => function () {
    return ($this->privates['.service_locator.vGud83Y'] ?? $this->load('get_ServiceLocator_VGud83YService.php'));
}, 'App\\Controller\\DeliveryBagController:show' => function () {
    return ($this->privates['.service_locator.4un_9ql'] ?? $this->load('get_ServiceLocator_4un9qlService.php'));
}, 'App\\Controller\\DeliveryBagController:showCart' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\DeliveryBagController:unsetCart' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\DeliveryBagController:validateCart' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\DeliveryController:delete' => function () {
    return ($this->privates['.service_locator.jVPgoOe'] ?? $this->load('get_ServiceLocator_JVPgoOeService.php'));
}, 'App\\Controller\\DeliveryController:edit' => function () {
    return ($this->privates['.service_locator.jVPgoOe'] ?? $this->load('get_ServiceLocator_JVPgoOeService.php'));
}, 'App\\Controller\\DeliveryController:index' => function () {
    return ($this->privates['.service_locator.ptnIIWn'] ?? $this->load('get_ServiceLocator_PtnIIWnService.php'));
}, 'App\\Controller\\DeliveryController:show' => function () {
    return ($this->privates['.service_locator.jVPgoOe'] ?? $this->load('get_ServiceLocator_JVPgoOeService.php'));
}, 'App\\Controller\\DonationBagController:delete' => function () {
    return ($this->privates['.service_locator.3WLkTWh'] ?? $this->load('get_ServiceLocator_3WLkTWhService.php'));
}, 'App\\Controller\\DonationBagController:edit' => function () {
    return ($this->privates['.service_locator.3WLkTWh'] ?? $this->load('get_ServiceLocator_3WLkTWhService.php'));
}, 'App\\Controller\\DonationBagController:index' => function () {
    return ($this->privates['.service_locator.b5pjVLS'] ?? $this->load('get_ServiceLocator_B5pjVLSService.php'));
}, 'App\\Controller\\DonationBagController:show' => function () {
    return ($this->privates['.service_locator.3WLkTWh'] ?? $this->load('get_ServiceLocator_3WLkTWhService.php'));
}, 'App\\Controller\\FabricController:delete' => function () {
    return ($this->privates['.service_locator.j6g6xTt'] ?? $this->load('get_ServiceLocator_J6g6xTtService.php'));
}, 'App\\Controller\\FabricController:edit' => function () {
    return ($this->privates['.service_locator.j6g6xTt'] ?? $this->load('get_ServiceLocator_J6g6xTtService.php'));
}, 'App\\Controller\\FabricController:index' => function () {
    return ($this->privates['.service_locator.eWPu2Tx'] ?? $this->load('get_ServiceLocator_EWPu2TxService.php'));
}, 'App\\Controller\\FabricController:show' => function () {
    return ($this->privates['.service_locator.j6g6xTt'] ?? $this->load('get_ServiceLocator_J6g6xTtService.php'));
}, 'App\\Controller\\HomeController:concept' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\HomeController:show' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\KidController:create' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController:admin' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController:delete' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController:edit' => function () {
    return ($this->privates['.service_locator.Goy7jhH'] ?? $this->load('get_ServiceLocator_Goy7jhHService.php'));
}, 'App\\Controller\\MemberController:index' => function () {
    return ($this->privates['.service_locator.uO5nSH6'] ?? $this->load('get_ServiceLocator_UO5nSH6Service.php'));
}, 'App\\Controller\\MemberController:new' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController:setSession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\MemberController:show' => function () {
    return ($this->privates['.service_locator.Goy7jhH'] ?? $this->load('get_ServiceLocator_Goy7jhHService.php'));
}, 'App\\Controller\\MemberController:unsetSession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\NewsController:delete' => function () {
    return ($this->privates['.service_locator.Ncno5IG'] ?? $this->load('get_ServiceLocator_Ncno5IGService.php'));
}, 'App\\Controller\\NewsController:edit' => function () {
    return ($this->privates['.service_locator.Ncno5IG'] ?? $this->load('get_ServiceLocator_Ncno5IGService.php'));
}, 'App\\Controller\\NewsController:index' => function () {
    return ($this->privates['.service_locator.SAjoI7s'] ?? $this->load('get_ServiceLocator_SAjoI7sService.php'));
}, 'App\\Controller\\NewsController:show' => function () {
    return ($this->privates['.service_locator.Ncno5IG'] ?? $this->load('get_ServiceLocator_Ncno5IGService.php'));
}, 'App\\Controller\\SchoolController:delete' => function () {
    return ($this->privates['.service_locator.yAd9_DO'] ?? $this->load('get_ServiceLocator_YAd9DOService.php'));
}, 'App\\Controller\\SchoolController:edit' => function () {
    return ($this->privates['.service_locator.yAd9_DO'] ?? $this->load('get_ServiceLocator_YAd9DOService.php'));
}, 'App\\Controller\\SchoolController:index' => function () {
    return ($this->privates['.service_locator.08aQTYo'] ?? $this->load('get_ServiceLocator_08aQTYoService.php'));
}, 'App\\Controller\\SchoolController:show' => function () {
    return ($this->privates['.service_locator.yAd9_DO'] ?? $this->load('get_ServiceLocator_YAd9DOService.php'));
}, 'App\\Controller\\SchoolStopController:delete' => function () {
    return ($this->privates['.service_locator.vg9rx_y'] ?? $this->load('get_ServiceLocator_Vg9rxYService.php'));
}, 'App\\Controller\\SchoolStopController:edit' => function () {
    return ($this->privates['.service_locator.vg9rx_y'] ?? $this->load('get_ServiceLocator_Vg9rxYService.php'));
}, 'App\\Controller\\SchoolStopController:index' => function () {
    return ($this->privates['.service_locator.1Y1uG8Q'] ?? $this->load('get_ServiceLocator_1Y1uG8QService.php'));
}, 'App\\Controller\\SchoolStopController:show' => function () {
    return ($this->privates['.service_locator.vg9rx_y'] ?? $this->load('get_ServiceLocator_Vg9rxYService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\SecurityController:registration' => function () {
    return ($this->privates['.service_locator.rFr3Ijd'] ?? $this->load('get_ServiceLocator_RFr3IjdService.php'));
}, 'App\\Controller\\WorkshopController:book' => function () {
    return ($this->privates['.service_locator.hXT.oGW'] ?? $this->load('get_ServiceLocator_HXT_OGWService.php'));
}, 'App\\Controller\\WorkshopController:delete' => function () {
    return ($this->privates['.service_locator.Zc3jyJQ'] ?? $this->load('get_ServiceLocator_Zc3jyJQService.php'));
}, 'App\\Controller\\WorkshopController:edit' => function () {
    return ($this->privates['.service_locator.Zc3jyJQ'] ?? $this->load('get_ServiceLocator_Zc3jyJQService.php'));
}, 'App\\Controller\\WorkshopController:index' => function () {
    return ($this->privates['.service_locator.MabVHwZ'] ?? $this->load('get_ServiceLocator_MabVHwZService.php'));
}, 'App\\Controller\\WorkshopController:pay' => function () {
    return ($this->privates['.service_locator.hXT.oGW'] ?? $this->load('get_ServiceLocator_HXT_OGWService.php'));
}, 'App\\Controller\\WorkshopController:show' => function () {
    return ($this->privates['.service_locator.Zc3jyJQ'] ?? $this->load('get_ServiceLocator_Zc3jyJQService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
