<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.vg9rx_y.App\Entity\SchoolStop' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.vg9rx_y": it references class "App\\Entity\\SchoolStop" but no such service exists.');
