<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Member extends \App\Entity\Member implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_name', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_surname', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_address1', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_address2', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_zip_code', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_city', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_tel', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_email', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_password', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_button_wallet', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_subscription', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_expertise', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_level', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_kid_list', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_kid_count', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_worshopAsTrainer', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_worshopAsTrainee', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_donationBag_list', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_deliveryBag_list', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_role'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_name', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_surname', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_address1', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_address2', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_zip_code', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_city', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_tel', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_email', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_password', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_button_wallet', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_subscription', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_expertise', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_level', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_kid_list', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_kid_count', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_worshopAsTrainer', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_worshopAsTrainee', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_donationBag_list', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_deliveryBag_list', '' . "\0" . 'App\\Entity\\Member' . "\0" . 'member_role'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Member $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberName', []);

        return parent::getMemberName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberName(string $member_name): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberName', [$member_name]);

        return parent::setMemberName($member_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberSurname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberSurname', []);

        return parent::getMemberSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberSurname(string $member_surname): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberSurname', [$member_surname]);

        return parent::setMemberSurname($member_surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberAddress1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberAddress1', []);

        return parent::getMemberAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberAddress1(?string $member_address1): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberAddress1', [$member_address1]);

        return parent::setMemberAddress1($member_address1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberAddress2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberAddress2', []);

        return parent::getMemberAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberAddress2(?string $member_address2): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberAddress2', [$member_address2]);

        return parent::setMemberAddress2($member_address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberZipCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberZipCode', []);

        return parent::getMemberZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberZipCode(?string $member_zip_code): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberZipCode', [$member_zip_code]);

        return parent::setMemberZipCode($member_zip_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberCity', []);

        return parent::getMemberCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberCity(?string $member_city): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberCity', [$member_city]);

        return parent::setMemberCity($member_city);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberTel', []);

        return parent::getMemberTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberTel(?string $member_tel): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberTel', [$member_tel]);

        return parent::setMemberTel($member_tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberEmail', []);

        return parent::getMemberEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberEmail(string $member_email): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberEmail', [$member_email]);

        return parent::setMemberEmail($member_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberPassword', []);

        return parent::getMemberPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberPassword(string $member_password): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberPassword', [$member_password]);

        return parent::setMemberPassword($member_password);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberButtonWallet(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberButtonWallet', []);

        return parent::getMemberButtonWallet();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberButtonWallet(?int $member_button_wallet): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberButtonWallet', [$member_button_wallet]);

        return parent::setMemberButtonWallet($member_button_wallet);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberSubscription(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberSubscription', []);

        return parent::getMemberSubscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberSubscription(bool $member_subscription): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberSubscription', [$member_subscription]);

        return parent::setMemberSubscription($member_subscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberExpertise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberExpertise', []);

        return parent::getMemberExpertise();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberExpertise(?string $member_expertise): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberExpertise', [$member_expertise]);

        return parent::setMemberExpertise($member_expertise);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberLevel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberLevel', []);

        return parent::getMemberLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberLevel(?string $member_level): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberLevel', [$member_level]);

        return parent::setMemberLevel($member_level);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberKidList(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberKidList', []);

        return parent::getMemberKidList();
    }

    /**
     * {@inheritDoc}
     */
    public function addMemberKidList(\App\Entity\Kid $memberKidList): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMemberKidList', [$memberKidList]);

        return parent::addMemberKidList($memberKidList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMemberKidList(\App\Entity\Kid $memberKidList): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMemberKidList', [$memberKidList]);

        return parent::removeMemberKidList($memberKidList);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberKidCount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberKidCount', []);

        return parent::getMemberKidCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberKidCount(int $member_kid_count): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberKidCount', [$member_kid_count]);

        return parent::setMemberKidCount($member_kid_count);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberWorshopAsTrainer(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberWorshopAsTrainer', []);

        return parent::getMemberWorshopAsTrainer();
    }

    /**
     * {@inheritDoc}
     */
    public function addMemberWorshopAsTrainer(\App\Entity\Workshop $memberWorshopAsTrainer): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMemberWorshopAsTrainer', [$memberWorshopAsTrainer]);

        return parent::addMemberWorshopAsTrainer($memberWorshopAsTrainer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMemberWorshopAsTrainer(\App\Entity\Workshop $memberWorshopAsTrainer): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMemberWorshopAsTrainer', [$memberWorshopAsTrainer]);

        return parent::removeMemberWorshopAsTrainer($memberWorshopAsTrainer);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberWorshopAsTrainee(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberWorshopAsTrainee', []);

        return parent::getMemberWorshopAsTrainee();
    }

    /**
     * {@inheritDoc}
     */
    public function addMemberWorshopAsTrainee(\App\Entity\Workshop $memberWorshopAsTrainee): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMemberWorshopAsTrainee', [$memberWorshopAsTrainee]);

        return parent::addMemberWorshopAsTrainee($memberWorshopAsTrainee);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMemberWorshopAsTrainee(\App\Entity\Workshop $memberWorshopAsTrainee): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMemberWorshopAsTrainee', [$memberWorshopAsTrainee]);

        return parent::removeMemberWorshopAsTrainee($memberWorshopAsTrainee);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberDonationBagList(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberDonationBagList', []);

        return parent::getMemberDonationBagList();
    }

    /**
     * {@inheritDoc}
     */
    public function addMemberDonationBagList(\App\Entity\DonationBag $memberDonationBagList): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMemberDonationBagList', [$memberDonationBagList]);

        return parent::addMemberDonationBagList($memberDonationBagList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMemberDonationBagList(\App\Entity\DonationBag $memberDonationBagList): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMemberDonationBagList', [$memberDonationBagList]);

        return parent::removeMemberDonationBagList($memberDonationBagList);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberDeliveryBagList(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberDeliveryBagList', []);

        return parent::getMemberDeliveryBagList();
    }

    /**
     * {@inheritDoc}
     */
    public function addMemberDeliveryBagList(\App\Entity\DeliveryBag $memberDeliveryBagList): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMemberDeliveryBagList', [$memberDeliveryBagList]);

        return parent::addMemberDeliveryBagList($memberDeliveryBagList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMemberDeliveryBagList(\App\Entity\DeliveryBag $memberDeliveryBagList): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMemberDeliveryBagList', [$memberDeliveryBagList]);

        return parent::removeMemberDeliveryBagList($memberDeliveryBagList);
    }

    /**
     * {@inheritDoc}
     */
    public function getMemberRole(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemberRole', []);

        return parent::getMemberRole();
    }

    /**
     * {@inheritDoc}
     */
    public function addMemberRole(\App\Entity\Role $memberRole): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMemberRole', [$memberRole]);

        return parent::addMemberRole($memberRole);
    }

    /**
     * {@inheritDoc}
     */
    public function setMemberRole(\App\Entity\Role $memberRole): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMemberRole', [$memberRole]);

        return parent::setMemberRole($memberRole);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMemberRole(\App\Entity\Role $memberRole): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMemberRole', [$memberRole]);

        return parent::removeMemberRole($memberRole);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', []);

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $member_password): \App\Entity\Member
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$member_password]);

        return parent::setPassword($member_password);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

}
