<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class School extends \App\Entity\School implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\School' . "\0" . 'id', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_name', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_address1', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_address2', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_zip_code', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_city', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_gender', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_name', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_tel', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_email', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_kid_list'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\School' . "\0" . 'id', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_name', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_address1', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_address2', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_zip_code', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_city', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_gender', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_name', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_tel', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_director_email', '' . "\0" . 'App\\Entity\\School' . "\0" . 'school_kid_list'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (School $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolName', []);

        return parent::getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolName(string $school_name): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolName', [$school_name]);

        return parent::setSchoolName($school_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolAddress1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolAddress1', []);

        return parent::getSchoolAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolAddress1(?string $school_address1): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolAddress1', [$school_address1]);

        return parent::setSchoolAddress1($school_address1);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolAddress2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolAddress2', []);

        return parent::getSchoolAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolAddress2(?string $school_address2): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolAddress2', [$school_address2]);

        return parent::setSchoolAddress2($school_address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolZipCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolZipCode', []);

        return parent::getSchoolZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolZipCode(?string $school_zip_code): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolZipCode', [$school_zip_code]);

        return parent::setSchoolZipCode($school_zip_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolCity', []);

        return parent::getSchoolCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolCity(string $school_city): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolCity', [$school_city]);

        return parent::setSchoolCity($school_city);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolDirectorGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolDirectorGender', []);

        return parent::getSchoolDirectorGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolDirectorGender(string $school_director_gender): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolDirectorGender', [$school_director_gender]);

        return parent::setSchoolDirectorGender($school_director_gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolDirectorName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolDirectorName', []);

        return parent::getSchoolDirectorName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolDirectorName(string $school_director_name): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolDirectorName', [$school_director_name]);

        return parent::setSchoolDirectorName($school_director_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolDirectorTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolDirectorTel', []);

        return parent::getSchoolDirectorTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolDirectorTel(?string $school_director_tel): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolDirectorTel', [$school_director_tel]);

        return parent::setSchoolDirectorTel($school_director_tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolDirectorEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolDirectorEmail', []);

        return parent::getSchoolDirectorEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchoolDirectorEmail(?string $school_director_email): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchoolDirectorEmail', [$school_director_email]);

        return parent::setSchoolDirectorEmail($school_director_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolKidList(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolKidList', []);

        return parent::getSchoolKidList();
    }

    /**
     * {@inheritDoc}
     */
    public function addSchoolKidList(\App\Entity\Kid $schoolKidList): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSchoolKidList', [$schoolKidList]);

        return parent::addSchoolKidList($schoolKidList);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSchoolKidList(\App\Entity\Kid $schoolKidList): \App\Entity\School
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSchoolKidList', [$schoolKidList]);

        return parent::removeSchoolKidList($schoolKidList);
    }

}
