<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.i9EFuuj' shared service.

return $this->privates['.service_locator.i9EFuuj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('deliveryBagRepository' => function (): \App\Repository\DeliveryBagRepository {
    return ($this->privates['App\Repository\DeliveryBagRepository'] ?? $this->load('getDeliveryBagRepositoryService.php'));
}));
