<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ArticleController:index' => function () {
    return ($this->privates['service_locator.bpFMXcb'] ?? $this->load('getServiceLocator_BpFMXcbService.php'));
}, 'App\\Controller\\ArticleController:selection' => function () {
    return ($this->privates['service_locator.CYE44gG'] ?? $this->load('getServiceLocator_CYE44gGService.php'));
}, 'App\\Controller\\DeliveryBagController:addToCart' => function () {
    return ($this->privates['service_locator.6f3AKN.'] ?? $this->load('getServiceLocator_6f3AKN_Service.php'));
}, 'App\\Controller\\DeliveryBagController:index' => function () {
    return ($this->privates['service_locator.7Lg8Ahu'] ?? $this->load('getServiceLocator_7Lg8AhuService.php'));
}, 'App\\Controller\\DeliveryBagController:removeFromCart' => function () {
    return ($this->privates['service_locator.6f3AKN.'] ?? $this->load('getServiceLocator_6f3AKN_Service.php'));
}, 'App\\Controller\\DeliveryBagController:showCart' => function () {
    return ($this->privates['service_locator.f_mztkY'] ?? $this->load('getServiceLocator_FMztkYService.php'));
}, 'App\\Controller\\DeliveryBagController:unsetCart' => function () {
    return ($this->privates['service_locator.f_mztkY'] ?? $this->load('getServiceLocator_FMztkYService.php'));
}, 'App\\Controller\\DeliveryBagController:validateCart' => function () {
    return ($this->privates['service_locator.f_mztkY'] ?? $this->load('getServiceLocator_FMztkYService.php'));
}, 'App\\Controller\\DeliveryController:index' => function () {
    return ($this->privates['service_locator.KmOKDit'] ?? $this->load('getServiceLocator_KmOKDitService.php'));
}, 'App\\Controller\\DonationBagController:index' => function () {
    return ($this->privates['service_locator.qNrsnym'] ?? $this->load('getServiceLocator_QNrsnymService.php'));
}, 'App\\Controller\\FabricController:index' => function () {
    return ($this->privates['service_locator.zSgYK9s'] ?? $this->load('getServiceLocator_ZSgYK9sService.php'));
}, 'App\\Controller\\HomeController:concept' => function () {
    return ($this->privates['service_locator.Tl7T0UP'] ?? $this->load('getServiceLocator_Tl7T0UPService.php'));
}, 'App\\Controller\\HomeController:show' => function () {
    return ($this->privates['service_locator.Tl7T0UP'] ?? $this->load('getServiceLocator_Tl7T0UPService.php'));
}, 'App\\Controller\\KidController:create' => function () {
    return ($this->privates['service_locator.X5a2Zog'] ?? $this->load('getServiceLocator_X5a2ZogService.php'));
}, 'App\\Controller\\MemberController:admin' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController:delete' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController:edit' => function () {
    return ($this->privates['service_locator.avi.qY5'] ?? $this->load('getServiceLocator_Avi_QY5Service.php'));
}, 'App\\Controller\\MemberController:index' => function () {
    return ($this->privates['service_locator.VcV1ToB'] ?? $this->load('getServiceLocator_VcV1ToBService.php'));
}, 'App\\Controller\\MemberController:new' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController:setSession' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController:show' => function () {
    return ($this->privates['service_locator.avi.qY5'] ?? $this->load('getServiceLocator_Avi_QY5Service.php'));
}, 'App\\Controller\\MemberController:unsetSession' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\NewsController:index' => function () {
    return ($this->privates['service_locator.a7ZWpw6'] ?? $this->load('getServiceLocator_A7ZWpw6Service.php'));
}, 'App\\Controller\\SchoolController:index' => function () {
    return ($this->privates['service_locator.YdCMxCd'] ?? $this->load('getServiceLocator_YdCMxCdService.php'));
}, 'App\\Controller\\SchoolStopController:index' => function () {
    return ($this->privates['service_locator.aKou2fE'] ?? $this->load('getServiceLocator_AKou2fEService.php'));
}, 'App\\Controller\\WorkshopController:book' => function () {
    return ($this->privates['service_locator.W0kHhQ7'] ?? $this->load('getServiceLocator_W0kHhQ7Service.php'));
}, 'App\\Controller\\WorkshopController:index' => function () {
    return ($this->privates['service_locator.FDFXJ06'] ?? $this->load('getServiceLocator_FDFXJ06Service.php'));
}, 'App\\Controller\\WorkshopController:pay' => function () {
    return ($this->privates['service_locator.W0kHhQ7'] ?? $this->load('getServiceLocator_W0kHhQ7Service.php'));
}, 'App\\Controller\\ArticleController::index' => function () {
    return ($this->privates['service_locator.bpFMXcb'] ?? $this->load('getServiceLocator_BpFMXcbService.php'));
}, 'App\\Controller\\ArticleController::selection' => function () {
    return ($this->privates['service_locator.CYE44gG'] ?? $this->load('getServiceLocator_CYE44gGService.php'));
}, 'App\\Controller\\DeliveryBagController::addToCart' => function () {
    return ($this->privates['service_locator.6f3AKN.'] ?? $this->load('getServiceLocator_6f3AKN_Service.php'));
}, 'App\\Controller\\DeliveryBagController::index' => function () {
    return ($this->privates['service_locator.7Lg8Ahu'] ?? $this->load('getServiceLocator_7Lg8AhuService.php'));
}, 'App\\Controller\\DeliveryBagController::removeFromCart' => function () {
    return ($this->privates['service_locator.6f3AKN.'] ?? $this->load('getServiceLocator_6f3AKN_Service.php'));
}, 'App\\Controller\\DeliveryBagController::showCart' => function () {
    return ($this->privates['service_locator.f_mztkY'] ?? $this->load('getServiceLocator_FMztkYService.php'));
}, 'App\\Controller\\DeliveryBagController::unsetCart' => function () {
    return ($this->privates['service_locator.f_mztkY'] ?? $this->load('getServiceLocator_FMztkYService.php'));
}, 'App\\Controller\\DeliveryBagController::validateCart' => function () {
    return ($this->privates['service_locator.f_mztkY'] ?? $this->load('getServiceLocator_FMztkYService.php'));
}, 'App\\Controller\\DeliveryController::index' => function () {
    return ($this->privates['service_locator.KmOKDit'] ?? $this->load('getServiceLocator_KmOKDitService.php'));
}, 'App\\Controller\\DonationBagController::index' => function () {
    return ($this->privates['service_locator.qNrsnym'] ?? $this->load('getServiceLocator_QNrsnymService.php'));
}, 'App\\Controller\\FabricController::index' => function () {
    return ($this->privates['service_locator.zSgYK9s'] ?? $this->load('getServiceLocator_ZSgYK9sService.php'));
}, 'App\\Controller\\HomeController::concept' => function () {
    return ($this->privates['service_locator.Tl7T0UP'] ?? $this->load('getServiceLocator_Tl7T0UPService.php'));
}, 'App\\Controller\\HomeController::show' => function () {
    return ($this->privates['service_locator.Tl7T0UP'] ?? $this->load('getServiceLocator_Tl7T0UPService.php'));
}, 'App\\Controller\\KidController::create' => function () {
    return ($this->privates['service_locator.X5a2Zog'] ?? $this->load('getServiceLocator_X5a2ZogService.php'));
}, 'App\\Controller\\MemberController::admin' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController::delete' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController::edit' => function () {
    return ($this->privates['service_locator.avi.qY5'] ?? $this->load('getServiceLocator_Avi_QY5Service.php'));
}, 'App\\Controller\\MemberController::index' => function () {
    return ($this->privates['service_locator.VcV1ToB'] ?? $this->load('getServiceLocator_VcV1ToBService.php'));
}, 'App\\Controller\\MemberController::new' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController::setSession' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\MemberController::show' => function () {
    return ($this->privates['service_locator.avi.qY5'] ?? $this->load('getServiceLocator_Avi_QY5Service.php'));
}, 'App\\Controller\\MemberController::unsetSession' => function () {
    return ($this->privates['service_locator.1pPGPr4'] ?? $this->load('getServiceLocator_1pPGPr4Service.php'));
}, 'App\\Controller\\NewsController::index' => function () {
    return ($this->privates['service_locator.a7ZWpw6'] ?? $this->load('getServiceLocator_A7ZWpw6Service.php'));
}, 'App\\Controller\\SchoolController::index' => function () {
    return ($this->privates['service_locator.YdCMxCd'] ?? $this->load('getServiceLocator_YdCMxCdService.php'));
}, 'App\\Controller\\SchoolStopController::index' => function () {
    return ($this->privates['service_locator.aKou2fE'] ?? $this->load('getServiceLocator_AKou2fEService.php'));
}, 'App\\Controller\\WorkshopController::book' => function () {
    return ($this->privates['service_locator.W0kHhQ7'] ?? $this->load('getServiceLocator_W0kHhQ7Service.php'));
}, 'App\\Controller\\WorkshopController::index' => function () {
    return ($this->privates['service_locator.FDFXJ06'] ?? $this->load('getServiceLocator_FDFXJ06Service.php'));
}, 'App\\Controller\\WorkshopController::pay' => function () {
    return ($this->privates['service_locator.W0kHhQ7'] ?? $this->load('getServiceLocator_W0kHhQ7Service.php'));
})));
