<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.orm.default_entity_manager' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/NamingStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/QuoteStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/EntityListenerResolver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Mapping/EntityListenerServiceResolver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Mapping/ContainerAwareEntityListenerResolver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/RepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Configuration.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/ManagerConfigurator.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/ObjectManager.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php';

$a = new \Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain();
$a->addDriver(new \Doctrine\ORM\Mapping\Driver\AnnotationDriver(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()), array(0 => ($this->targetDirs[3].'/src/Entity'))), 'App\\Entity');

$b = new \Doctrine\ORM\Configuration();
$b->setEntityNamespaces(array('App' => 'App\\Entity'));
$b->setMetadataCacheImpl(($this->services['doctrine_cache.providers.doctrine.orm.default_metadata_cache'] ?? $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultMetadataCacheService.php')));
$b->setQueryCacheImpl(($this->services['doctrine_cache.providers.doctrine.orm.default_query_cache'] ?? $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultQueryCacheService.php')));
$b->setResultCacheImpl(($this->services['doctrine_cache.providers.doctrine.orm.default_result_cache'] ?? $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultResultCacheService.php')));
$b->setMetadataDriverImpl($a);
$b->setProxyDir(($this->targetDirs[0].'/doctrine/orm/Proxies'));
$b->setProxyNamespace('Proxies');
$b->setAutoGenerateProxyClasses(true);
$b->setClassMetadataFactoryName('Doctrine\\ORM\\Mapping\\ClassMetadataFactory');
$b->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
$b->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy());
$b->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
$b->setEntityListenerResolver(new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerAwareEntityListenerResolver($this));
$b->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Repository\\ArticleRepository' => function () {
    return ($this->privates['App\Repository\ArticleRepository'] ?? $this->load('getArticleRepositoryService.php'));
}, 'App\\Repository\\BrandRepository' => function () {
    return ($this->privates['App\Repository\BrandRepository'] ?? $this->load('getBrandRepositoryService.php'));
}, 'App\\Repository\\ColorRepository' => function () {
    return ($this->privates['App\Repository\ColorRepository'] ?? $this->load('getColorRepositoryService.php'));
}, 'App\\Repository\\DeliveryBagRepository' => function () {
    return ($this->privates['App\Repository\DeliveryBagRepository'] ?? $this->load('getDeliveryBagRepositoryService.php'));
}, 'App\\Repository\\DeliveryRepository' => function () {
    return ($this->privates['App\Repository\DeliveryRepository'] ?? $this->load('getDeliveryRepositoryService.php'));
}, 'App\\Repository\\DonationBagRepository' => function () {
    return ($this->privates['App\Repository\DonationBagRepository'] ?? $this->load('getDonationBagRepositoryService.php'));
}, 'App\\Repository\\FabricRepository' => function () {
    return ($this->privates['App\Repository\FabricRepository'] ?? $this->load('getFabricRepositoryService.php'));
}, 'App\\Repository\\GenderRepository' => function () {
    return ($this->privates['App\Repository\GenderRepository'] ?? $this->load('getGenderRepositoryService.php'));
}, 'App\\Repository\\KidRepository' => function () {
    return ($this->privates['App\Repository\KidRepository'] ?? $this->load('getKidRepositoryService.php'));
}, 'App\\Repository\\MemberRepository' => function () {
    return ($this->privates['App\Repository\MemberRepository'] ?? $this->load('getMemberRepositoryService.php'));
}, 'App\\Repository\\NewsRepository' => function () {
    return ($this->privates['App\Repository\NewsRepository'] ?? $this->load('getNewsRepositoryService.php'));
}, 'App\\Repository\\ProcessStatusRepository' => function () {
    return ($this->privates['App\Repository\ProcessStatusRepository'] ?? $this->load('getProcessStatusRepositoryService.php'));
}, 'App\\Repository\\RoleRepository' => function () {
    return ($this->privates['App\Repository\RoleRepository'] ?? $this->load('getRoleRepositoryService.php'));
}, 'App\\Repository\\SchoolRepository' => function () {
    return ($this->privates['App\Repository\SchoolRepository'] ?? $this->load('getSchoolRepositoryService.php'));
}, 'App\\Repository\\SchoolStopRepository' => function () {
    return ($this->privates['App\Repository\SchoolStopRepository'] ?? $this->load('getSchoolStopRepositoryService.php'));
}, 'App\\Repository\\SeasonRepository' => function () {
    return ($this->privates['App\Repository\SeasonRepository'] ?? $this->load('getSeasonRepositoryService.php'));
}, 'App\\Repository\\SizeRepository' => function () {
    return ($this->privates['App\Repository\SizeRepository'] ?? $this->load('getSizeRepositoryService.php'));
}, 'App\\Repository\\TypeRepository' => function () {
    return ($this->privates['App\Repository\TypeRepository'] ?? $this->load('getTypeRepositoryService.php'));
}, 'App\\Repository\\WearStatusRepository' => function () {
    return ($this->privates['App\Repository\WearStatusRepository'] ?? $this->load('getWearStatusRepositoryService.php'));
}, 'App\\Repository\\WorkshopRepository' => function () {
    return ($this->privates['App\Repository\WorkshopRepository'] ?? $this->load('getWorkshopRepositoryService.php'));
}))));

$this->services['doctrine.orm.default_entity_manager'] = $instance = \Doctrine\ORM\EntityManager::create(($this->services['doctrine.dbal.default_connection'] ?? $this->load('getDoctrine_Dbal_DefaultConnectionService.php')), $b);

(new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator(array(), array()))->configure($instance);

return $instance;
