<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry(array(0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Form\\ArticleType' => function () {
    return ($this->privates['App\Form\ArticleType'] ?? $this->privates['App\Form\ArticleType'] = new \App\Form\ArticleType());
}, 'App\\Form\\DeliveryBagType' => function () {
    return ($this->privates['App\Form\DeliveryBagType'] ?? $this->privates['App\Form\DeliveryBagType'] = new \App\Form\DeliveryBagType());
}, 'App\\Form\\DeliveryType' => function () {
    return ($this->privates['App\Form\DeliveryType'] ?? $this->privates['App\Form\DeliveryType'] = new \App\Form\DeliveryType());
}, 'App\\Form\\DonationBagType' => function () {
    return ($this->privates['App\Form\DonationBagType'] ?? $this->privates['App\Form\DonationBagType'] = new \App\Form\DonationBagType());
}, 'App\\Form\\FabricType' => function () {
    return ($this->privates['App\Form\FabricType'] ?? $this->privates['App\Form\FabricType'] = new \App\Form\FabricType());
}, 'App\\Form\\KidType' => function () {
    return ($this->privates['App\Form\KidType'] ?? $this->privates['App\Form\KidType'] = new \App\Form\KidType());
}, 'App\\Form\\MemberType' => function () {
    return ($this->privates['App\Form\MemberType'] ?? $this->privates['App\Form\MemberType'] = new \App\Form\MemberType());
}, 'App\\Form\\NewsType' => function () {
    return ($this->privates['App\Form\NewsType'] ?? $this->privates['App\Form\NewsType'] = new \App\Form\NewsType());
}, 'App\\Form\\SchoolStopType' => function () {
    return ($this->privates['App\Form\SchoolStopType'] ?? $this->privates['App\Form\SchoolStopType'] = new \App\Form\SchoolStopType());
}, 'App\\Form\\SchoolType' => function () {
    return ($this->privates['App\Form\SchoolType'] ?? $this->privates['App\Form\SchoolType'] = new \App\Form\SchoolType());
}, 'App\\Form\\WorkshopType' => function () {
    return ($this->privates['App\Form\WorkshopType'] ?? $this->privates['App\Form\WorkshopType'] = new \App\Form\WorkshopType());
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ($this->privates['form.type.entity'] ?? $this->load('getForm_Type_EntityService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ($this->privates['form.type.choice'] ?? $this->load('getForm_Type_ChoiceService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ($this->privates['form.type.form'] ?? $this->load('getForm_Type_FormService.php'));
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 1 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 2 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
}, 4), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? $this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? $this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
}, 1)), new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))), ($this->privates['form.resolved_type_factory'] ?? $this->privates['form.resolved_type_factory'] = new \Symfony\Component\Form\ResolvedFormTypeFactory()));
