<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDd73vix\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDd73vix/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDd73vix.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDd73vix\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDd73vix\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dd73vix',
    'container.build_id' => '7d9327cd',
    'container.build_time' => 1541452715,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDd73vix');
