<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDhmrg9B\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDhmrg9B/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDhmrg9B.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDhmrg9B\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDhmrg9B\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dhmrg9B',
    'container.build_id' => '181c7997',
    'container.build_time' => 1541357832,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDhmrg9B');
